### ISSUE TITLE
issue in namespace in version 1.0.1

### ISSUE THREAD

**Issue by ahmad-samir** [bilginnet/yii2-cropper#11]
Namespace in the composer file in release [1.0.1](https://github.com/bilginnet/yii2-cropper/releases/tag/1.0.1)  should equal to "bilginnet\\\cropper\\" not "bilginnet\\plupload\\"

**Comment by bilginnet** [comment]
please update with composer

**Comment by ashrafakl** [comment]
This issue still exists.
