### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Request' not found 

### ISSUE THREAD

**Issue by asifrafeeq** [bilginnet/yii2-cropper#12]
Fatal error: Uncaught Error: Class 'Request' not found in C:\xampp\htdocs\myapp\backend\config\main.php:10 Stack trace: #0 C:\xampp\htdocs\myapp\backend\web\index.php(13): require() #1 {main} thrown in C:\xampp\htdocs\myapp\backend\config\main.php on line 10

I think Request class is not there, how to include it. ?
 $baseUrl = str_replace('/backend/web', '', (new Request)->getBaseUrl());
    $baseUrl = str_replace('/frontend/web', '', $baseUrl);

**Comment by bilginnet** [comment]
use yii\web\Request;
or 
$baseUrl = str_replace('/backend/web', '', (new \yii\web\Request)->getBaseUrl());
