### ISSUE TITLE
Height cropper?

### ISSUE THREAD

**Issue by mydesign** [bilginnet/yii2-cropper#13]
how to fix width and resize height? or turn on "free" in this widget?

**Comment by bilginnet** [comment]
You can set width and height attribute if you want to crop an image. And you can set "imageUrl" attribute if you want to recrop an image. Look at the "advanced usage"...
Why are you need to crop an image if you want free aspect ratio..? Dont crop image, just upload with my plupload widget: [https://github.com/bilginnet/yii2-plupload](https://github.com/bilginnet/yii2-plupload)
