### ISSUE TITLE
issue in namespace in version 1.0.1 still exists

### ISSUE THREAD

**Issue by ashrafakl** [bilginnet/yii2-cropper#14]
This issue #11 still exists
The psr4 in composer file still equal to "bilginnet\\plupload\\"

**Comment by bilginnet** [comment]
i checked it. namespace is not bilginnet\plupload in all version

**Comment by ashrafakl** [comment]
@bilginnet Sorry but the namespace in composer is still equal to "bilginnet\plupload\"

I added "bilginnet/yii2-cropper": "~1.0.1" to my project  and after run composer update in terminal, I checked composer.json inside myproject/vendor/bilginnet/yii2-cropper, and it is the same as the file in the following link
https://github.com/bilginnet/yii2-cropper/blob/1.0.1/composer.json
