### ISSUE TITLE
An asset bundle that depends on 'yii\web\YiiAsset' has a higher javascript file position configured than 'yii\web\YiiAsset'.

### ISSUE THREAD

**Issue by metola** [bilginnet/yii2-cropper#3]
Hi, I have a problem with position assets, in my asset put this:

public $jsOptions = ['position' => \yii\web\View::POS_HEAD];
because I need, but I get a error.
If I change in CropperAsset.php :
 POS_HEAD for POS_END
this fix, but I don´t know if this is correct.

**Comment by bilginnet** [comment]
please install again; and you can use like this

jsOptions = [
   'pos' => View::POS_HEAD,
]

**Comment by mahmutt** [comment]
in backend/config/main.php components array   add following code block:
`'assetManager' => [
			'bundles' => [
				'yii\web\JqueryAsset' => [
					'jsOptions' => [ 'position' => \yii\web\View::POS_HEAD ],
				],
			],
		],`
